name: Run tests
on:
  push:
    branches:
      - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install CLI for TLA
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            tlacli
      
      - name: Run bash test script
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh
        shell: bash
